### ISSUE TITLE
【css】学习

### ISSUE THREAD

**Issue by cxcxy** [cxcxy/Vue-Study-Project#6]
**css id 选择器**
id选择器可以为标有特定id的HTML元素指定特定的样式。
id选择器以“#”来定义。
```html
<p id="red">这个段落是红色。</p>
<p id="green">这个段落是绿色。</p>
```
```css
#red {color:red;}
#green {color:green;}
```
**id 属性只能在每个HTML文档中出线一次**
**id选择器和派生选择器**
在现代布局中，id选择器常常用于建议派生选择器
```css
#sidebar p {
	font-style: italic;
	text-align: right;
	margin-top: 0.5em;
	}
#sidebar h2 {
	font-size: 1em;
	}
```
**CSS类选择器**
在CSS中，类选择器以一个点号显示，也可被用作派生选择器
```html
<h1 class="center">
This heading will be center-aligned
</h1>
```
```css
.center {text-align: center}
.fancy td {
	color: #f60;
	background: #666;
	}
```
