### ISSUE TITLE
【CSS】定位

### ISSUE THREAD

**Issue by cxcxy** [cxcxy/Vue-Study-Project#8]
### 相对定位
**position: relative**
```css
#box_relative {
  position: relative;
  left: 30px;
  top: 20px;
}
```
![image](https://user-images.githubusercontent.com/15125631/42260517-5c61f53c-7f97-11e8-8368-62e4eba1228a.png)
注意，在使用相对定位时，无论是否进行移动，元素仍然占据原来的空间。因此，移动元素会导致它覆盖其它框
### 绝对定位
**position: absolute**
```css
#box_relative {
  position: absolute;
  left: 30px;
  top: 20px;
}
```
如下图所示：
![image](https://user-images.githubusercontent.com/15125631/42260603-aade5e9e-7f97-11e8-8e2b-178535cf28bd.png)
绝对定位的元素的位置相对于最近的已定位祖先元素，如果元素没有已定位的祖先元素，那么它的位置相对于最初的包含块。

对于定位的主要问题是要记住每种定位的意义。所以，现在让我们复习一下学过的知识吧：相对定位是“相对于”元素在文档中的初始位置，而绝对定位是“相对于”最近的已定位祖先元素，如果不存在已定位的祖先元素，那么“相对于”最初的包含块。
